spring:
  profiles:
    active: dev

---
server:
  port: 8205
spring:
  profiles: dev
  application:
    name: config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

---
server:
  port: 8206
spring:
  profiles: test
  application:
    name: config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/