
spring:
  profiles:
    active: dev

---
spring:
  profile: dev
  application:
    name: config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

---
spring:
  profile: test
  application:
    name: config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/